export const AGING_CONSTANTS = {
  BASE_SHADOW_SIZE: 5,
  MAX_SHADOW_SIZE: 30,
  BASE_SEPIA: 70,
  MAX_SEPIA: 80,
};

export const ITEM_DIMENSIONS = {
  IMAGE_MAX_WIDTH: 400,
  TEXT_MAX_WIDTH: 300,
  LINK_MAX_WIDTH: 350,
}; 